---
- name: "systemv - Create Xvfb deamon script"
  template:
        src=init-xvfb.j2
        dest=/etc/init.d/xvfb
        mode=755

- name: "systemv - Configure Xvfb automatic startup < 16.04"
  service:
        name=xvfb
        pattern=/usr/bin/Xvfb
        enabled=yes
        state=started

